services:
  - type: web
    name: farmpower-backend
    runtime: docker
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        fromDatabase:
          name: farmpower-db
          property: connectionString
    plan: free
    numInstances: 1
    healthCheckPath: /docs
    autoDeploy: true

databases:
  - name: farmpower-db
    databaseName: farmpower
    user: farmpower_user
    plan: free
