services:
  - type: web
    name: farmpower-backend
    runtime: docker
    dockerContext: ./farmpower_backend_v2
    dockerfilePath: Dockerfile
    
    # Health check configuration
    healthCheckPath: /health
    
    # Enable auto-deploy
    autoDeploy: true
    
    # Environment variables
    envVars:
      # Server Configuration
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: "8000"
      - key: ENVIRONMENT
        value: production
      - key: FORWARDED_ALLOW_IPS
        value: "*"
      
      # Python Configuration
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONPATH
        value: /app
      
      # Network Optimization
      - key: NETWORK_IPV6
        value: "no"
      - key: RES_OPTIONS
        value: "rotate timeout:1 attempts:1"
      
      # Database Configuration
      - key: DATABASE_URL
        fromDatabase:
          name: farmpower-db
          property: connectionString
      - key: SQLALCHEMY_DATABASE_URL
        fromDatabase:
          name: farmpower-db
          property: connectionString
      
      # Connection Pool Settings
      - key: DB_POOL_SIZE
        value: "5"
      - key: DB_MAX_OVERFLOW
        value: "10"
      - key: DB_POOL_RECYCLE
        value: "300"
      - key: DB_POOL_TIMEOUT
        value: "30"
      
      # Supabase Configuration
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false  # Set in Render dashboard
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false  # Set in Render dashboard
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false  # Set in Render dashboard
      - key: SUPABASE_URL
        sync: false  # Set in Render dashboard
      - key: SUPABASE_KEY
        sync: false  # Set in Render dashboard
      
      # Timezone
      - key: TZ
        value: UTC
    
    # Build command
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt
    
    # Start command using gunicorn with optimized settings
    startCommand: >-
      gunicorn app.main:app \
      --workers 4 \
      --worker-class uvicorn.workers.UvicornWorker \
      --bind 0.0.0.0:$PORT \
      --timeout 120 \
      --keep-alive 60 \
      --max-requests 1000 \
      --max-requests-jitter 50 \
      --log-level info \
      --access-logfile - \
      --error-logfile - \
      --proxy-protocol \
      --forwarded-allow-ips="*"
      
      # Security
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: ALLOWED_ORIGINS
        value: "https://your-frontend-domain.com,http://localhost:3000"
      - key: SECURE_PROXY_SSL_HEADER
        value: "('HTTP_X_FORWARDED_PROTO', 'https')"
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: CSRF_COOKIE_SECURE
        value: "true"
      - key: SECURE_SSL_REDIRECT
        value: "true"
      
      # Optional Settings
      - key: LOG_LEVEL
        value: "INFO"
      - key: WORKERS
        value: "2"
      - key: TIMEOUT
        value: "120"
      - key: KEEP_ALIVE
        value: "5"
    plan: free
    numInstances: 1
    region: oregon  # Choose your preferred region

databases:
  - name: farmpower-db
    databaseName: farmpower
    user: farmpower_user
    plan: free
