services:
  - type: web
    name: farmpower-backend
    runtime: docker
    buildCommand: |
      cd farmpower_backend_v2 && \
      pip install -r requirements.txt
    startCommand: >-
      cd farmpower_backend_v2 && \
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        fromDatabase:
          name: farmpower-db
          property: connectionString
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: ${NEXT_PUBLIC_SUPABASE_URL}
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: ${SUPABASE_SERVICE_ROLE_KEY}
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
    plan: free
    numInstances: 1
    healthCheckPath: /docs
    autoDeploy: true
    region: oregon  # Choose your preferred region

databases:
  - name: farmpower-db
    databaseName: farmpower
    user: farmpower_user
    plan: free
