services:
  - type: web
    name: farmpower-backend
    runtime: docker
    buildCommand: |
      pip install -r /app/farmpower_backend_v2/requirements.txt
    startCommand: >-
      cd /app/farmpower_backend_v2 && \
      uvicorn main:app --host 0.0.0.0 --port $PORT --proxy-headers
    envVars:
      # Server Configuration
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: "8000"
      - key: ENVIRONMENT
        value: production
      
      # Python Configuration
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: /app
      
      # Database Configuration
      - key: DATABASE_URL
        fromDatabase:
          name: farmpower-db
          property: connectionString
      
      # Supabase Configuration
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false  # Set in Render dashboard
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false  # Set in Render dashboard
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false  # Set in Render dashboard
      
      # Security
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: ALLOWED_ORIGINS
        value: "https://your-frontend-domain.com,http://localhost:3000"
      
      # Optional Settings
      - key: LOG_LEVEL
        value: "INFO"
      - key: WORKERS
        value: "2"
      - key: TIMEOUT
        value: "120"
      - key: KEEP_ALIVE
        value: "5"
    plan: free
    numInstances: 1
    healthCheckPath: /docs
    autoDeploy: true
    region: oregon  # Choose your preferred region

databases:
  - name: farmpower-db
    databaseName: farmpower
    user: farmpower_user
    plan: free
