"""Initial migration

Revision ID: f184f6721e88
Revises: 
Create Date: 2025-06-21 03:51:45.658431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f184f6721e88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_calculations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crop_calculations', 'updated_at')
    # ### end Alembic commands ###
