version: '3.8'
services:
  test-db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farmpower_test
    ports:
      - "5433:5432"  # Use a different port to avoid conflicts
    volumes:
      - test-db-data:/var/lib/postgresql/data

volumes:
  test-db-data: